// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef PROTOBUF_rpc_2eproto__INCLUDED
#define PROTOBUF_rpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class AddTracksReq;
class AddTracksReqDefaultTypeInternal;
extern AddTracksReqDefaultTypeInternal _AddTracksReq_default_instance_;
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class Frag;
class FragDefaultTypeInternal;
extern FragDefaultTypeInternal _Frag_default_instance_;
class NewPCReq;
class NewPCReqDefaultTypeInternal;
extern NewPCReqDefaultTypeInternal _NewPCReq_default_instance_;
class NewPCRes;
class NewPCResDefaultTypeInternal;
extern NewPCResDefaultTypeInternal _NewPCRes_default_instance_;
class NewTrackSrcsRes;
class NewTrackSrcsResDefaultTypeInternal;
extern NewTrackSrcsResDefaultTypeInternal _NewTrackSrcsRes_default_instance_;
class NewUrlTracksReq;
class NewUrlTracksReqDefaultTypeInternal;
extern NewUrlTracksReqDefaultTypeInternal _NewUrlTracksReq_default_instance_;
class NewUrlTracksRes;
class NewUrlTracksResDefaultTypeInternal;
extern NewUrlTracksResDefaultTypeInternal _NewUrlTracksRes_default_instance_;
class OfferAnswerReq;
class OfferAnswerReqDefaultTypeInternal;
extern OfferAnswerReqDefaultTypeInternal _OfferAnswerReq_default_instance_;
class OfferAnswerRes;
class OfferAnswerResDefaultTypeInternal;
extern OfferAnswerResDefaultTypeInternal _OfferAnswerRes_default_instance_;
class OnTrackPacketMsg;
class OnTrackPacketMsgDefaultTypeInternal;
extern OnTrackPacketMsgDefaultTypeInternal _OnTrackPacketMsg_default_instance_;
class Packet;
class PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
class Result;
class ResultDefaultTypeInternal;
extern ResultDefaultTypeInternal _Result_default_instance_;
class SetDescReq;
class SetDescReqDefaultTypeInternal;
extern SetDescReqDefaultTypeInternal _SetDescReq_default_instance_;
class SetDescRes;
class SetDescResDefaultTypeInternal;
extern SetDescResDefaultTypeInternal _SetDescRes_default_instance_;
class TrackSrc;
class TrackSrcDefaultTypeInternal;
extern TrackSrcDefaultTypeInternal _TrackSrc_default_instance_;
class TrackSrcSendPacketReq;
class TrackSrcSendPacketReqDefaultTypeInternal;
extern TrackSrcSendPacketReqDefaultTypeInternal _TrackSrcSendPacketReq_default_instance_;

namespace protobuf_rpc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_rpc_2eproto

enum TrackType {
  VIDEO = 0,
  AUDIO = 1,
  TrackType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  TrackType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TrackType_IsValid(int value);
const TrackType TrackType_MIN = VIDEO;
const TrackType TrackType_MAX = AUDIO;
const int TrackType_ARRAYSIZE = TrackType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TrackType_descriptor();
inline const ::std::string& TrackType_Name(TrackType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TrackType_descriptor(), value);
}
inline bool TrackType_Parse(
    const ::std::string& name, TrackType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TrackType>(
    TrackType_descriptor(), name, value);
}
// ===================================================================

class Result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Result) */ {
 public:
  Result();
  virtual ~Result();

  Result(const Result& from);

  inline Result& operator=(const Result& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Result& default_instance();

  static inline const Result* internal_default_instance() {
    return reinterpret_cast<const Result*>(
               &_Result_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(Result* other);

  // implements Message ----------------------------------------------

  inline Result* New() const PROTOBUF_FINAL { return New(NULL); }

  Result* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Result& from);
  void MergeFrom(const Result& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error = 10001;
  void clear_error();
  static const int kErrorFieldNumber = 10001;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // int64 code = 10000;
  void clear_code();
  static const int kCodeFieldNumber = 10000;
  ::google::protobuf::int64 code() const;
  void set_code(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Result)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  ::google::protobuf::int64 code_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewPCReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewPCReq) */ {
 public:
  NewPCReq();
  virtual ~NewPCReq();

  NewPCReq(const NewPCReq& from);

  inline NewPCReq& operator=(const NewPCReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewPCReq& default_instance();

  static inline const NewPCReq* internal_default_instance() {
    return reinterpret_cast<const NewPCReq*>(
               &_NewPCReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(NewPCReq* other);

  // implements Message ----------------------------------------------

  inline NewPCReq* New() const PROTOBUF_FINAL { return New(NULL); }

  NewPCReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewPCReq& from);
  void MergeFrom(const NewPCReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewPCReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:NewPCReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewPCRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewPCRes) */ {
 public:
  NewPCRes();
  virtual ~NewPCRes();

  NewPCRes(const NewPCRes& from);

  inline NewPCRes& operator=(const NewPCRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewPCRes& default_instance();

  static inline const NewPCRes* internal_default_instance() {
    return reinterpret_cast<const NewPCRes*>(
               &_NewPCRes_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(NewPCRes* other);

  // implements Message ----------------------------------------------

  inline NewPCRes* New() const PROTOBUF_FINAL { return New(NULL); }

  NewPCRes* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewPCRes& from);
  void MergeFrom(const NewPCRes& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewPCRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Result res = 1;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 1;
  const ::Result& res() const;
  ::Result* mutable_res();
  ::Result* release_res();
  void set_allocated_res(::Result* res);

  // uint64 pcid = 2;
  void clear_pcid();
  static const int kPcidFieldNumber = 2;
  ::google::protobuf::uint64 pcid() const;
  void set_pcid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:NewPCRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Result* res_;
  ::google::protobuf::uint64 pcid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetDescReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SetDescReq) */ {
 public:
  SetDescReq();
  virtual ~SetDescReq();

  SetDescReq(const SetDescReq& from);

  inline SetDescReq& operator=(const SetDescReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetDescReq& default_instance();

  static inline const SetDescReq* internal_default_instance() {
    return reinterpret_cast<const SetDescReq*>(
               &_SetDescReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(SetDescReq* other);

  // implements Message ----------------------------------------------

  inline SetDescReq* New() const PROTOBUF_FINAL { return New(NULL); }

  SetDescReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetDescReq& from);
  void MergeFrom(const SetDescReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetDescReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // string sdp = 5;
  void clear_sdp();
  static const int kSdpFieldNumber = 5;
  const ::std::string& sdp() const;
  void set_sdp(const ::std::string& value);
  #if LANG_CXX11
  void set_sdp(::std::string&& value);
  #endif
  void set_sdp(const char* value);
  void set_sdp(const char* value, size_t size);
  ::std::string* mutable_sdp();
  ::std::string* release_sdp();
  void set_allocated_sdp(::std::string* sdp);

  // uint64 pcid = 3;
  void clear_pcid();
  static const int kPcidFieldNumber = 3;
  ::google::protobuf::uint64 pcid() const;
  void set_pcid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:SetDescReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr sdp_;
  ::google::protobuf::uint64 pcid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetDescRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SetDescRes) */ {
 public:
  SetDescRes();
  virtual ~SetDescRes();

  SetDescRes(const SetDescRes& from);

  inline SetDescRes& operator=(const SetDescRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetDescRes& default_instance();

  static inline const SetDescRes* internal_default_instance() {
    return reinterpret_cast<const SetDescRes*>(
               &_SetDescRes_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(SetDescRes* other);

  // implements Message ----------------------------------------------

  inline SetDescRes* New() const PROTOBUF_FINAL { return New(NULL); }

  SetDescRes* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetDescRes& from);
  void MergeFrom(const SetDescRes& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetDescRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sdp = 7;
  void clear_sdp();
  static const int kSdpFieldNumber = 7;
  const ::std::string& sdp() const;
  void set_sdp(const ::std::string& value);
  #if LANG_CXX11
  void set_sdp(::std::string&& value);
  #endif
  void set_sdp(const char* value);
  void set_sdp(const char* value, size_t size);
  ::std::string* mutable_sdp();
  ::std::string* release_sdp();
  void set_allocated_sdp(::std::string* sdp);

  // .Result res = 6;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 6;
  const ::Result& res() const;
  ::Result* mutable_res();
  ::Result* release_res();
  void set_allocated_res(::Result* res);

  // @@protoc_insertion_point(class_scope:SetDescRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sdp_;
  ::Result* res_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OfferAnswerReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OfferAnswerReq) */ {
 public:
  OfferAnswerReq();
  virtual ~OfferAnswerReq();

  OfferAnswerReq(const OfferAnswerReq& from);

  inline OfferAnswerReq& operator=(const OfferAnswerReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OfferAnswerReq& default_instance();

  static inline const OfferAnswerReq* internal_default_instance() {
    return reinterpret_cast<const OfferAnswerReq*>(
               &_OfferAnswerReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(OfferAnswerReq* other);

  // implements Message ----------------------------------------------

  inline OfferAnswerReq* New() const PROTOBUF_FINAL { return New(NULL); }

  OfferAnswerReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OfferAnswerReq& from);
  void MergeFrom(const OfferAnswerReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OfferAnswerReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool audio = 9;
  void clear_audio();
  static const int kAudioFieldNumber = 9;
  bool audio() const;
  void set_audio(bool value);

  // bool video = 10;
  void clear_video();
  static const int kVideoFieldNumber = 10;
  bool video() const;
  void set_video(bool value);

  // uint64 pcid = 8;
  void clear_pcid();
  static const int kPcidFieldNumber = 8;
  ::google::protobuf::uint64 pcid() const;
  void set_pcid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:OfferAnswerReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool audio_;
  bool video_;
  ::google::protobuf::uint64 pcid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OfferAnswerRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OfferAnswerRes) */ {
 public:
  OfferAnswerRes();
  virtual ~OfferAnswerRes();

  OfferAnswerRes(const OfferAnswerRes& from);

  inline OfferAnswerRes& operator=(const OfferAnswerRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OfferAnswerRes& default_instance();

  static inline const OfferAnswerRes* internal_default_instance() {
    return reinterpret_cast<const OfferAnswerRes*>(
               &_OfferAnswerRes_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(OfferAnswerRes* other);

  // implements Message ----------------------------------------------

  inline OfferAnswerRes* New() const PROTOBUF_FINAL { return New(NULL); }

  OfferAnswerRes* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OfferAnswerRes& from);
  void MergeFrom(const OfferAnswerRes& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OfferAnswerRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sdp = 12;
  void clear_sdp();
  static const int kSdpFieldNumber = 12;
  const ::std::string& sdp() const;
  void set_sdp(const ::std::string& value);
  #if LANG_CXX11
  void set_sdp(::std::string&& value);
  #endif
  void set_sdp(const char* value);
  void set_sdp(const char* value, size_t size);
  ::std::string* mutable_sdp();
  ::std::string* release_sdp();
  void set_allocated_sdp(::std::string* sdp);

  // .Result res = 11;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 11;
  const ::Result& res() const;
  ::Result* mutable_res();
  ::Result* release_res();
  void set_allocated_res(::Result* res);

  // @@protoc_insertion_point(class_scope:OfferAnswerRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sdp_;
  ::Result* res_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TrackSrc : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TrackSrc) */ {
 public:
  TrackSrc();
  virtual ~TrackSrc();

  TrackSrc(const TrackSrc& from);

  inline TrackSrc& operator=(const TrackSrc& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrackSrc& default_instance();

  static inline const TrackSrc* internal_default_instance() {
    return reinterpret_cast<const TrackSrc*>(
               &_TrackSrc_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(TrackSrc* other);

  // implements Message ----------------------------------------------

  inline TrackSrc* New() const PROTOBUF_FINAL { return New(NULL); }

  TrackSrc* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TrackSrc& from);
  void MergeFrom(const TrackSrc& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TrackSrc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .TrackType type = 14;
  void clear_type();
  static const int kTypeFieldNumber = 14;
  ::TrackType type() const;
  void set_type(::TrackType value);

  // uint64 tsid = 13;
  void clear_tsid();
  static const int kTsidFieldNumber = 13;
  ::google::protobuf::uint64 tsid() const;
  void set_tsid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:TrackSrc)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  ::google::protobuf::uint64 tsid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewUrlTracksReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewUrlTracksReq) */ {
 public:
  NewUrlTracksReq();
  virtual ~NewUrlTracksReq();

  NewUrlTracksReq(const NewUrlTracksReq& from);

  inline NewUrlTracksReq& operator=(const NewUrlTracksReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewUrlTracksReq& default_instance();

  static inline const NewUrlTracksReq* internal_default_instance() {
    return reinterpret_cast<const NewUrlTracksReq*>(
               &_NewUrlTracksReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(NewUrlTracksReq* other);

  // implements Message ----------------------------------------------

  inline NewUrlTracksReq* New() const PROTOBUF_FINAL { return New(NULL); }

  NewUrlTracksReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewUrlTracksReq& from);
  void MergeFrom(const NewUrlTracksReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewUrlTracksReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string url = 15;
  void clear_url();
  static const int kUrlFieldNumber = 15;
  const ::std::string& url() const;
  void set_url(const ::std::string& value);
  #if LANG_CXX11
  void set_url(::std::string&& value);
  #endif
  void set_url(const char* value);
  void set_url(const char* value, size_t size);
  ::std::string* mutable_url();
  ::std::string* release_url();
  void set_allocated_url(::std::string* url);

  // @@protoc_insertion_point(class_scope:NewUrlTracksReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr url_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewUrlTracksRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewUrlTracksRes) */ {
 public:
  NewUrlTracksRes();
  virtual ~NewUrlTracksRes();

  NewUrlTracksRes(const NewUrlTracksRes& from);

  inline NewUrlTracksRes& operator=(const NewUrlTracksRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewUrlTracksRes& default_instance();

  static inline const NewUrlTracksRes* internal_default_instance() {
    return reinterpret_cast<const NewUrlTracksRes*>(
               &_NewUrlTracksRes_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(NewUrlTracksRes* other);

  // implements Message ----------------------------------------------

  inline NewUrlTracksRes* New() const PROTOBUF_FINAL { return New(NULL); }

  NewUrlTracksRes* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewUrlTracksRes& from);
  void MergeFrom(const NewUrlTracksRes& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewUrlTracksRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .TrackSrc trackSrcs = 17;
  int tracksrcs_size() const;
  void clear_tracksrcs();
  static const int kTrackSrcsFieldNumber = 17;
  const ::TrackSrc& tracksrcs(int index) const;
  ::TrackSrc* mutable_tracksrcs(int index);
  ::TrackSrc* add_tracksrcs();
  ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
      mutable_tracksrcs();
  const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
      tracksrcs() const;

  // .Result res = 16;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 16;
  const ::Result& res() const;
  ::Result* mutable_res();
  ::Result* release_res();
  void set_allocated_res(::Result* res);

  // @@protoc_insertion_point(class_scope:NewUrlTracksRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::TrackSrc > tracksrcs_;
  ::Result* res_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewTrackSrcsRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NewTrackSrcsRes) */ {
 public:
  NewTrackSrcsRes();
  virtual ~NewTrackSrcsRes();

  NewTrackSrcsRes(const NewTrackSrcsRes& from);

  inline NewTrackSrcsRes& operator=(const NewTrackSrcsRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewTrackSrcsRes& default_instance();

  static inline const NewTrackSrcsRes* internal_default_instance() {
    return reinterpret_cast<const NewTrackSrcsRes*>(
               &_NewTrackSrcsRes_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(NewTrackSrcsRes* other);

  // implements Message ----------------------------------------------

  inline NewTrackSrcsRes* New() const PROTOBUF_FINAL { return New(NULL); }

  NewTrackSrcsRes* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewTrackSrcsRes& from);
  void MergeFrom(const NewTrackSrcsRes& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewTrackSrcsRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .TrackSrc trackSrcs = 19;
  int tracksrcs_size() const;
  void clear_tracksrcs();
  static const int kTrackSrcsFieldNumber = 19;
  const ::TrackSrc& tracksrcs(int index) const;
  ::TrackSrc* mutable_tracksrcs(int index);
  ::TrackSrc* add_tracksrcs();
  ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
      mutable_tracksrcs();
  const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
      tracksrcs() const;

  // .Result res = 18;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 18;
  const ::Result& res() const;
  ::Result* mutable_res();
  ::Result* release_res();
  void set_allocated_res(::Result* res);

  // @@protoc_insertion_point(class_scope:NewTrackSrcsRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::TrackSrc > tracksrcs_;
  ::Result* res_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Frag : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Frag) */ {
 public:
  Frag();
  virtual ~Frag();

  Frag(const Frag& from);

  inline Frag& operator=(const Frag& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Frag& default_instance();

  static inline const Frag* internal_default_instance() {
    return reinterpret_cast<const Frag*>(
               &_Frag_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(Frag* other);

  // implements Message ----------------------------------------------

  inline Frag* New() const PROTOBUF_FINAL { return New(NULL); }

  Frag* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Frag& from);
  void MergeFrom(const Frag& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Frag* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 off = 20;
  void clear_off();
  static const int kOffFieldNumber = 20;
  ::google::protobuf::uint64 off() const;
  void set_off(::google::protobuf::uint64 value);

  // uint64 len = 21;
  void clear_len();
  static const int kLenFieldNumber = 21;
  ::google::protobuf::uint64 len() const;
  void set_len(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Frag)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 off_;
  ::google::protobuf::uint64 len_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TrackSrcSendPacketReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TrackSrcSendPacketReq) */ {
 public:
  TrackSrcSendPacketReq();
  virtual ~TrackSrcSendPacketReq();

  TrackSrcSendPacketReq(const TrackSrcSendPacketReq& from);

  inline TrackSrcSendPacketReq& operator=(const TrackSrcSendPacketReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrackSrcSendPacketReq& default_instance();

  static inline const TrackSrcSendPacketReq* internal_default_instance() {
    return reinterpret_cast<const TrackSrcSendPacketReq*>(
               &_TrackSrcSendPacketReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(TrackSrcSendPacketReq* other);

  // implements Message ----------------------------------------------

  inline TrackSrcSendPacketReq* New() const PROTOBUF_FINAL { return New(NULL); }

  TrackSrcSendPacketReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TrackSrcSendPacketReq& from);
  void MergeFrom(const TrackSrcSendPacketReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TrackSrcSendPacketReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Packet pkt = 22;
  bool has_pkt() const;
  void clear_pkt();
  static const int kPktFieldNumber = 22;
  const ::Packet& pkt() const;
  ::Packet* mutable_pkt();
  ::Packet* release_pkt();
  void set_allocated_pkt(::Packet* pkt);

  // uint64 tsid = 21;
  void clear_tsid();
  static const int kTsidFieldNumber = 21;
  ::google::protobuf::uint64 tsid() const;
  void set_tsid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:TrackSrcSendPacketReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Packet* pkt_;
  ::google::protobuf::uint64 tsid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Packet) */ {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  static inline const Packet* internal_default_instance() {
    return reinterpret_cast<const Packet*>(
               &_Packet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    13;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(Packet* other);

  // implements Message ----------------------------------------------

  inline Packet* New() const PROTOBUF_FINAL { return New(NULL); }

  Packet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Frag frags = 25;
  int frags_size() const;
  void clear_frags();
  static const int kFragsFieldNumber = 25;
  const ::Frag& frags(int index) const;
  ::Frag* mutable_frags(int index);
  ::Frag* add_frags();
  ::google::protobuf::RepeatedPtrField< ::Frag >*
      mutable_frags();
  const ::google::protobuf::RepeatedPtrField< ::Frag >&
      frags() const;

  // bytes buf = 24;
  void clear_buf();
  static const int kBufFieldNumber = 24;
  const ::std::string& buf() const;
  void set_buf(const ::std::string& value);
  #if LANG_CXX11
  void set_buf(::std::string&& value);
  #endif
  void set_buf(const char* value);
  void set_buf(const void* value, size_t size);
  ::std::string* mutable_buf();
  ::std::string* release_buf();
  void set_allocated_buf(::std::string* buf);

  // int32 nFrames = 29;
  void clear_nframes();
  static const int kNFramesFieldNumber = 29;
  ::google::protobuf::int32 nframes() const;
  void set_nframes(::google::protobuf::int32 value);

  // .TrackType type = 23;
  void clear_type();
  static const int kTypeFieldNumber = 23;
  ::TrackType type() const;
  void set_type(::TrackType value);

  // int32 sampleRate = 26;
  void clear_samplerate();
  static const int kSampleRateFieldNumber = 26;
  ::google::protobuf::int32 samplerate() const;
  void set_samplerate(::google::protobuf::int32 value);

  // int32 bitsPerSample = 27;
  void clear_bitspersample();
  static const int kBitsPerSampleFieldNumber = 27;
  ::google::protobuf::int32 bitspersample() const;
  void set_bitspersample(::google::protobuf::int32 value);

  // int32 nChannels = 28;
  void clear_nchannels();
  static const int kNChannelsFieldNumber = 28;
  ::google::protobuf::int32 nchannels() const;
  void set_nchannels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Packet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Frag > frags_;
  ::google::protobuf::internal::ArenaStringPtr buf_;
  ::google::protobuf::int32 nframes_;
  int type_;
  ::google::protobuf::int32 samplerate_;
  ::google::protobuf::int32 bitspersample_;
  ::google::protobuf::int32 nchannels_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OnTrackPacketMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OnTrackPacketMsg) */ {
 public:
  OnTrackPacketMsg();
  virtual ~OnTrackPacketMsg();

  OnTrackPacketMsg(const OnTrackPacketMsg& from);

  inline OnTrackPacketMsg& operator=(const OnTrackPacketMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnTrackPacketMsg& default_instance();

  static inline const OnTrackPacketMsg* internal_default_instance() {
    return reinterpret_cast<const OnTrackPacketMsg*>(
               &_OnTrackPacketMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    14;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(OnTrackPacketMsg* other);

  // implements Message ----------------------------------------------

  inline OnTrackPacketMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  OnTrackPacketMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OnTrackPacketMsg& from);
  void MergeFrom(const OnTrackPacketMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OnTrackPacketMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Packet pkt = 31;
  bool has_pkt() const;
  void clear_pkt();
  static const int kPktFieldNumber = 31;
  const ::Packet& pkt() const;
  ::Packet* mutable_pkt();
  ::Packet* release_pkt();
  void set_allocated_pkt(::Packet* pkt);

  // uint64 pcid = 30;
  void clear_pcid();
  static const int kPcidFieldNumber = 30;
  ::google::protobuf::uint64 pcid() const;
  void set_pcid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:OnTrackPacketMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Packet* pkt_;
  ::google::protobuf::uint64 pcid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AddTracksReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AddTracksReq) */ {
 public:
  AddTracksReq();
  virtual ~AddTracksReq();

  AddTracksReq(const AddTracksReq& from);

  inline AddTracksReq& operator=(const AddTracksReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddTracksReq& default_instance();

  static inline const AddTracksReq* internal_default_instance() {
    return reinterpret_cast<const AddTracksReq*>(
               &_AddTracksReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    15;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(AddTracksReq* other);

  // implements Message ----------------------------------------------

  inline AddTracksReq* New() const PROTOBUF_FINAL { return New(NULL); }

  AddTracksReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddTracksReq& from);
  void MergeFrom(const AddTracksReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddTracksReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .TrackSrc trackSrcs = 33;
  int tracksrcs_size() const;
  void clear_tracksrcs();
  static const int kTrackSrcsFieldNumber = 33;
  const ::TrackSrc& tracksrcs(int index) const;
  ::TrackSrc* mutable_tracksrcs(int index);
  ::TrackSrc* add_tracksrcs();
  ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
      mutable_tracksrcs();
  const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
      tracksrcs() const;

  // uint64 pcid = 32;
  void clear_pcid();
  static const int kPcidFieldNumber = 32;
  ::google::protobuf::uint64 pcid() const;
  void set_pcid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:AddTracksReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::TrackSrc > tracksrcs_;
  ::google::protobuf::uint64 pcid_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Empty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Empty) */ {
 public:
  Empty();
  virtual ~Empty();

  Empty(const Empty& from);

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Empty& default_instance();

  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    16;

  GOOGLE_ATTRIBUTE_NOINLINE void Swap(Empty* other);

  // implements Message ----------------------------------------------

  inline Empty* New() const PROTOBUF_FINAL { return New(NULL); }

  Empty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Empty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Empty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_rpc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Result

// int64 code = 10000;
inline void Result::clear_code() {
  code_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Result::code() const {
  // @@protoc_insertion_point(field_get:Result.code)
  return code_;
}
inline void Result::set_code(::google::protobuf::int64 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:Result.code)
}

// string error = 10001;
inline void Result::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Result::error() const {
  // @@protoc_insertion_point(field_get:Result.error)
  return error_.GetNoArena();
}
inline void Result::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Result.error)
}
#if LANG_CXX11
inline void Result::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Result.error)
}
#endif
inline void Result::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Result.error)
}
inline void Result::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Result.error)
}
inline ::std::string* Result::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:Result.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Result::release_error() {
  // @@protoc_insertion_point(field_release:Result.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Result::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:Result.error)
}

// -------------------------------------------------------------------

// NewPCReq

// -------------------------------------------------------------------

// NewPCRes

// .Result res = 1;
inline bool NewPCRes::has_res() const {
  return this != internal_default_instance() && res_ != NULL;
}
inline void NewPCRes::clear_res() {
  if (GetArenaNoVirtual() == NULL && res_ != NULL) delete res_;
  res_ = NULL;
}
inline const ::Result& NewPCRes::res() const {
  // @@protoc_insertion_point(field_get:NewPCRes.res)
  return res_ != NULL ? *res_
                         : *::Result::internal_default_instance();
}
inline ::Result* NewPCRes::mutable_res() {
  
  if (res_ == NULL) {
    res_ = new ::Result;
  }
  // @@protoc_insertion_point(field_mutable:NewPCRes.res)
  return res_;
}
inline ::Result* NewPCRes::release_res() {
  // @@protoc_insertion_point(field_release:NewPCRes.res)
  
  ::Result* temp = res_;
  res_ = NULL;
  return temp;
}
inline void NewPCRes::set_allocated_res(::Result* res) {
  delete res_;
  res_ = res;
  if (res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NewPCRes.res)
}

// uint64 pcid = 2;
inline void NewPCRes::clear_pcid() {
  pcid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewPCRes::pcid() const {
  // @@protoc_insertion_point(field_get:NewPCRes.pcid)
  return pcid_;
}
inline void NewPCRes::set_pcid(::google::protobuf::uint64 value) {
  
  pcid_ = value;
  // @@protoc_insertion_point(field_set:NewPCRes.pcid)
}

// -------------------------------------------------------------------

// SetDescReq

// uint64 pcid = 3;
inline void SetDescReq::clear_pcid() {
  pcid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SetDescReq::pcid() const {
  // @@protoc_insertion_point(field_get:SetDescReq.pcid)
  return pcid_;
}
inline void SetDescReq::set_pcid(::google::protobuf::uint64 value) {
  
  pcid_ = value;
  // @@protoc_insertion_point(field_set:SetDescReq.pcid)
}

// string type = 4;
inline void SetDescReq::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SetDescReq::type() const {
  // @@protoc_insertion_point(field_get:SetDescReq.type)
  return type_.GetNoArena();
}
inline void SetDescReq::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SetDescReq.type)
}
#if LANG_CXX11
inline void SetDescReq::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SetDescReq.type)
}
#endif
inline void SetDescReq::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SetDescReq.type)
}
inline void SetDescReq::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SetDescReq.type)
}
inline ::std::string* SetDescReq::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:SetDescReq.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetDescReq::release_type() {
  // @@protoc_insertion_point(field_release:SetDescReq.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetDescReq::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:SetDescReq.type)
}

// string sdp = 5;
inline void SetDescReq::clear_sdp() {
  sdp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SetDescReq::sdp() const {
  // @@protoc_insertion_point(field_get:SetDescReq.sdp)
  return sdp_.GetNoArena();
}
inline void SetDescReq::set_sdp(const ::std::string& value) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SetDescReq.sdp)
}
#if LANG_CXX11
inline void SetDescReq::set_sdp(::std::string&& value) {
  
  sdp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SetDescReq.sdp)
}
#endif
inline void SetDescReq::set_sdp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SetDescReq.sdp)
}
inline void SetDescReq::set_sdp(const char* value, size_t size) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SetDescReq.sdp)
}
inline ::std::string* SetDescReq::mutable_sdp() {
  
  // @@protoc_insertion_point(field_mutable:SetDescReq.sdp)
  return sdp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetDescReq::release_sdp() {
  // @@protoc_insertion_point(field_release:SetDescReq.sdp)
  
  return sdp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetDescReq::set_allocated_sdp(::std::string* sdp) {
  if (sdp != NULL) {
    
  } else {
    
  }
  sdp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sdp);
  // @@protoc_insertion_point(field_set_allocated:SetDescReq.sdp)
}

// -------------------------------------------------------------------

// SetDescRes

// .Result res = 6;
inline bool SetDescRes::has_res() const {
  return this != internal_default_instance() && res_ != NULL;
}
inline void SetDescRes::clear_res() {
  if (GetArenaNoVirtual() == NULL && res_ != NULL) delete res_;
  res_ = NULL;
}
inline const ::Result& SetDescRes::res() const {
  // @@protoc_insertion_point(field_get:SetDescRes.res)
  return res_ != NULL ? *res_
                         : *::Result::internal_default_instance();
}
inline ::Result* SetDescRes::mutable_res() {
  
  if (res_ == NULL) {
    res_ = new ::Result;
  }
  // @@protoc_insertion_point(field_mutable:SetDescRes.res)
  return res_;
}
inline ::Result* SetDescRes::release_res() {
  // @@protoc_insertion_point(field_release:SetDescRes.res)
  
  ::Result* temp = res_;
  res_ = NULL;
  return temp;
}
inline void SetDescRes::set_allocated_res(::Result* res) {
  delete res_;
  res_ = res;
  if (res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SetDescRes.res)
}

// string sdp = 7;
inline void SetDescRes::clear_sdp() {
  sdp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SetDescRes::sdp() const {
  // @@protoc_insertion_point(field_get:SetDescRes.sdp)
  return sdp_.GetNoArena();
}
inline void SetDescRes::set_sdp(const ::std::string& value) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SetDescRes.sdp)
}
#if LANG_CXX11
inline void SetDescRes::set_sdp(::std::string&& value) {
  
  sdp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SetDescRes.sdp)
}
#endif
inline void SetDescRes::set_sdp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SetDescRes.sdp)
}
inline void SetDescRes::set_sdp(const char* value, size_t size) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SetDescRes.sdp)
}
inline ::std::string* SetDescRes::mutable_sdp() {
  
  // @@protoc_insertion_point(field_mutable:SetDescRes.sdp)
  return sdp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetDescRes::release_sdp() {
  // @@protoc_insertion_point(field_release:SetDescRes.sdp)
  
  return sdp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetDescRes::set_allocated_sdp(::std::string* sdp) {
  if (sdp != NULL) {
    
  } else {
    
  }
  sdp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sdp);
  // @@protoc_insertion_point(field_set_allocated:SetDescRes.sdp)
}

// -------------------------------------------------------------------

// OfferAnswerReq

// uint64 pcid = 8;
inline void OfferAnswerReq::clear_pcid() {
  pcid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OfferAnswerReq::pcid() const {
  // @@protoc_insertion_point(field_get:OfferAnswerReq.pcid)
  return pcid_;
}
inline void OfferAnswerReq::set_pcid(::google::protobuf::uint64 value) {
  
  pcid_ = value;
  // @@protoc_insertion_point(field_set:OfferAnswerReq.pcid)
}

// bool audio = 9;
inline void OfferAnswerReq::clear_audio() {
  audio_ = false;
}
inline bool OfferAnswerReq::audio() const {
  // @@protoc_insertion_point(field_get:OfferAnswerReq.audio)
  return audio_;
}
inline void OfferAnswerReq::set_audio(bool value) {
  
  audio_ = value;
  // @@protoc_insertion_point(field_set:OfferAnswerReq.audio)
}

// bool video = 10;
inline void OfferAnswerReq::clear_video() {
  video_ = false;
}
inline bool OfferAnswerReq::video() const {
  // @@protoc_insertion_point(field_get:OfferAnswerReq.video)
  return video_;
}
inline void OfferAnswerReq::set_video(bool value) {
  
  video_ = value;
  // @@protoc_insertion_point(field_set:OfferAnswerReq.video)
}

// -------------------------------------------------------------------

// OfferAnswerRes

// .Result res = 11;
inline bool OfferAnswerRes::has_res() const {
  return this != internal_default_instance() && res_ != NULL;
}
inline void OfferAnswerRes::clear_res() {
  if (GetArenaNoVirtual() == NULL && res_ != NULL) delete res_;
  res_ = NULL;
}
inline const ::Result& OfferAnswerRes::res() const {
  // @@protoc_insertion_point(field_get:OfferAnswerRes.res)
  return res_ != NULL ? *res_
                         : *::Result::internal_default_instance();
}
inline ::Result* OfferAnswerRes::mutable_res() {
  
  if (res_ == NULL) {
    res_ = new ::Result;
  }
  // @@protoc_insertion_point(field_mutable:OfferAnswerRes.res)
  return res_;
}
inline ::Result* OfferAnswerRes::release_res() {
  // @@protoc_insertion_point(field_release:OfferAnswerRes.res)
  
  ::Result* temp = res_;
  res_ = NULL;
  return temp;
}
inline void OfferAnswerRes::set_allocated_res(::Result* res) {
  delete res_;
  res_ = res;
  if (res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OfferAnswerRes.res)
}

// string sdp = 12;
inline void OfferAnswerRes::clear_sdp() {
  sdp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OfferAnswerRes::sdp() const {
  // @@protoc_insertion_point(field_get:OfferAnswerRes.sdp)
  return sdp_.GetNoArena();
}
inline void OfferAnswerRes::set_sdp(const ::std::string& value) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OfferAnswerRes.sdp)
}
#if LANG_CXX11
inline void OfferAnswerRes::set_sdp(::std::string&& value) {
  
  sdp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:OfferAnswerRes.sdp)
}
#endif
inline void OfferAnswerRes::set_sdp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OfferAnswerRes.sdp)
}
inline void OfferAnswerRes::set_sdp(const char* value, size_t size) {
  
  sdp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OfferAnswerRes.sdp)
}
inline ::std::string* OfferAnswerRes::mutable_sdp() {
  
  // @@protoc_insertion_point(field_mutable:OfferAnswerRes.sdp)
  return sdp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OfferAnswerRes::release_sdp() {
  // @@protoc_insertion_point(field_release:OfferAnswerRes.sdp)
  
  return sdp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OfferAnswerRes::set_allocated_sdp(::std::string* sdp) {
  if (sdp != NULL) {
    
  } else {
    
  }
  sdp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sdp);
  // @@protoc_insertion_point(field_set_allocated:OfferAnswerRes.sdp)
}

// -------------------------------------------------------------------

// TrackSrc

// uint64 tsid = 13;
inline void TrackSrc::clear_tsid() {
  tsid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TrackSrc::tsid() const {
  // @@protoc_insertion_point(field_get:TrackSrc.tsid)
  return tsid_;
}
inline void TrackSrc::set_tsid(::google::protobuf::uint64 value) {
  
  tsid_ = value;
  // @@protoc_insertion_point(field_set:TrackSrc.tsid)
}

// .TrackType type = 14;
inline void TrackSrc::clear_type() {
  type_ = 0;
}
inline ::TrackType TrackSrc::type() const {
  // @@protoc_insertion_point(field_get:TrackSrc.type)
  return static_cast< ::TrackType >(type_);
}
inline void TrackSrc::set_type(::TrackType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:TrackSrc.type)
}

// -------------------------------------------------------------------

// NewUrlTracksReq

// string url = 15;
inline void NewUrlTracksReq::clear_url() {
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NewUrlTracksReq::url() const {
  // @@protoc_insertion_point(field_get:NewUrlTracksReq.url)
  return url_.GetNoArena();
}
inline void NewUrlTracksReq::set_url(const ::std::string& value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NewUrlTracksReq.url)
}
#if LANG_CXX11
inline void NewUrlTracksReq::set_url(::std::string&& value) {
  
  url_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NewUrlTracksReq.url)
}
#endif
inline void NewUrlTracksReq::set_url(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NewUrlTracksReq.url)
}
inline void NewUrlTracksReq::set_url(const char* value, size_t size) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NewUrlTracksReq.url)
}
inline ::std::string* NewUrlTracksReq::mutable_url() {
  
  // @@protoc_insertion_point(field_mutable:NewUrlTracksReq.url)
  return url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewUrlTracksReq::release_url() {
  // @@protoc_insertion_point(field_release:NewUrlTracksReq.url)
  
  return url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewUrlTracksReq::set_allocated_url(::std::string* url) {
  if (url != NULL) {
    
  } else {
    
  }
  url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), url);
  // @@protoc_insertion_point(field_set_allocated:NewUrlTracksReq.url)
}

// -------------------------------------------------------------------

// NewUrlTracksRes

// .Result res = 16;
inline bool NewUrlTracksRes::has_res() const {
  return this != internal_default_instance() && res_ != NULL;
}
inline void NewUrlTracksRes::clear_res() {
  if (GetArenaNoVirtual() == NULL && res_ != NULL) delete res_;
  res_ = NULL;
}
inline const ::Result& NewUrlTracksRes::res() const {
  // @@protoc_insertion_point(field_get:NewUrlTracksRes.res)
  return res_ != NULL ? *res_
                         : *::Result::internal_default_instance();
}
inline ::Result* NewUrlTracksRes::mutable_res() {
  
  if (res_ == NULL) {
    res_ = new ::Result;
  }
  // @@protoc_insertion_point(field_mutable:NewUrlTracksRes.res)
  return res_;
}
inline ::Result* NewUrlTracksRes::release_res() {
  // @@protoc_insertion_point(field_release:NewUrlTracksRes.res)
  
  ::Result* temp = res_;
  res_ = NULL;
  return temp;
}
inline void NewUrlTracksRes::set_allocated_res(::Result* res) {
  delete res_;
  res_ = res;
  if (res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NewUrlTracksRes.res)
}

// repeated .TrackSrc trackSrcs = 17;
inline int NewUrlTracksRes::tracksrcs_size() const {
  return tracksrcs_.size();
}
inline void NewUrlTracksRes::clear_tracksrcs() {
  tracksrcs_.Clear();
}
inline const ::TrackSrc& NewUrlTracksRes::tracksrcs(int index) const {
  // @@protoc_insertion_point(field_get:NewUrlTracksRes.trackSrcs)
  return tracksrcs_.Get(index);
}
inline ::TrackSrc* NewUrlTracksRes::mutable_tracksrcs(int index) {
  // @@protoc_insertion_point(field_mutable:NewUrlTracksRes.trackSrcs)
  return tracksrcs_.Mutable(index);
}
inline ::TrackSrc* NewUrlTracksRes::add_tracksrcs() {
  // @@protoc_insertion_point(field_add:NewUrlTracksRes.trackSrcs)
  return tracksrcs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
NewUrlTracksRes::mutable_tracksrcs() {
  // @@protoc_insertion_point(field_mutable_list:NewUrlTracksRes.trackSrcs)
  return &tracksrcs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
NewUrlTracksRes::tracksrcs() const {
  // @@protoc_insertion_point(field_list:NewUrlTracksRes.trackSrcs)
  return tracksrcs_;
}

// -------------------------------------------------------------------

// NewTrackSrcsRes

// .Result res = 18;
inline bool NewTrackSrcsRes::has_res() const {
  return this != internal_default_instance() && res_ != NULL;
}
inline void NewTrackSrcsRes::clear_res() {
  if (GetArenaNoVirtual() == NULL && res_ != NULL) delete res_;
  res_ = NULL;
}
inline const ::Result& NewTrackSrcsRes::res() const {
  // @@protoc_insertion_point(field_get:NewTrackSrcsRes.res)
  return res_ != NULL ? *res_
                         : *::Result::internal_default_instance();
}
inline ::Result* NewTrackSrcsRes::mutable_res() {
  
  if (res_ == NULL) {
    res_ = new ::Result;
  }
  // @@protoc_insertion_point(field_mutable:NewTrackSrcsRes.res)
  return res_;
}
inline ::Result* NewTrackSrcsRes::release_res() {
  // @@protoc_insertion_point(field_release:NewTrackSrcsRes.res)
  
  ::Result* temp = res_;
  res_ = NULL;
  return temp;
}
inline void NewTrackSrcsRes::set_allocated_res(::Result* res) {
  delete res_;
  res_ = res;
  if (res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NewTrackSrcsRes.res)
}

// repeated .TrackSrc trackSrcs = 19;
inline int NewTrackSrcsRes::tracksrcs_size() const {
  return tracksrcs_.size();
}
inline void NewTrackSrcsRes::clear_tracksrcs() {
  tracksrcs_.Clear();
}
inline const ::TrackSrc& NewTrackSrcsRes::tracksrcs(int index) const {
  // @@protoc_insertion_point(field_get:NewTrackSrcsRes.trackSrcs)
  return tracksrcs_.Get(index);
}
inline ::TrackSrc* NewTrackSrcsRes::mutable_tracksrcs(int index) {
  // @@protoc_insertion_point(field_mutable:NewTrackSrcsRes.trackSrcs)
  return tracksrcs_.Mutable(index);
}
inline ::TrackSrc* NewTrackSrcsRes::add_tracksrcs() {
  // @@protoc_insertion_point(field_add:NewTrackSrcsRes.trackSrcs)
  return tracksrcs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
NewTrackSrcsRes::mutable_tracksrcs() {
  // @@protoc_insertion_point(field_mutable_list:NewTrackSrcsRes.trackSrcs)
  return &tracksrcs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
NewTrackSrcsRes::tracksrcs() const {
  // @@protoc_insertion_point(field_list:NewTrackSrcsRes.trackSrcs)
  return tracksrcs_;
}

// -------------------------------------------------------------------

// Frag

// uint64 off = 20;
inline void Frag::clear_off() {
  off_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Frag::off() const {
  // @@protoc_insertion_point(field_get:Frag.off)
  return off_;
}
inline void Frag::set_off(::google::protobuf::uint64 value) {
  
  off_ = value;
  // @@protoc_insertion_point(field_set:Frag.off)
}

// uint64 len = 21;
inline void Frag::clear_len() {
  len_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Frag::len() const {
  // @@protoc_insertion_point(field_get:Frag.len)
  return len_;
}
inline void Frag::set_len(::google::protobuf::uint64 value) {
  
  len_ = value;
  // @@protoc_insertion_point(field_set:Frag.len)
}

// -------------------------------------------------------------------

// TrackSrcSendPacketReq

// uint64 tsid = 21;
inline void TrackSrcSendPacketReq::clear_tsid() {
  tsid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TrackSrcSendPacketReq::tsid() const {
  // @@protoc_insertion_point(field_get:TrackSrcSendPacketReq.tsid)
  return tsid_;
}
inline void TrackSrcSendPacketReq::set_tsid(::google::protobuf::uint64 value) {
  
  tsid_ = value;
  // @@protoc_insertion_point(field_set:TrackSrcSendPacketReq.tsid)
}

// .Packet pkt = 22;
inline bool TrackSrcSendPacketReq::has_pkt() const {
  return this != internal_default_instance() && pkt_ != NULL;
}
inline void TrackSrcSendPacketReq::clear_pkt() {
  if (GetArenaNoVirtual() == NULL && pkt_ != NULL) delete pkt_;
  pkt_ = NULL;
}
inline const ::Packet& TrackSrcSendPacketReq::pkt() const {
  // @@protoc_insertion_point(field_get:TrackSrcSendPacketReq.pkt)
  return pkt_ != NULL ? *pkt_
                         : *::Packet::internal_default_instance();
}
inline ::Packet* TrackSrcSendPacketReq::mutable_pkt() {
  
  if (pkt_ == NULL) {
    pkt_ = new ::Packet;
  }
  // @@protoc_insertion_point(field_mutable:TrackSrcSendPacketReq.pkt)
  return pkt_;
}
inline ::Packet* TrackSrcSendPacketReq::release_pkt() {
  // @@protoc_insertion_point(field_release:TrackSrcSendPacketReq.pkt)
  
  ::Packet* temp = pkt_;
  pkt_ = NULL;
  return temp;
}
inline void TrackSrcSendPacketReq::set_allocated_pkt(::Packet* pkt) {
  delete pkt_;
  pkt_ = pkt;
  if (pkt) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:TrackSrcSendPacketReq.pkt)
}

// -------------------------------------------------------------------

// Packet

// .TrackType type = 23;
inline void Packet::clear_type() {
  type_ = 0;
}
inline ::TrackType Packet::type() const {
  // @@protoc_insertion_point(field_get:Packet.type)
  return static_cast< ::TrackType >(type_);
}
inline void Packet::set_type(::TrackType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Packet.type)
}

// bytes buf = 24;
inline void Packet::clear_buf() {
  buf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Packet::buf() const {
  // @@protoc_insertion_point(field_get:Packet.buf)
  return buf_.GetNoArena();
}
inline void Packet::set_buf(const ::std::string& value) {
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Packet.buf)
}
#if LANG_CXX11
inline void Packet::set_buf(::std::string&& value) {
  
  buf_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Packet.buf)
}
#endif
inline void Packet::set_buf(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Packet.buf)
}
inline void Packet::set_buf(const void* value, size_t size) {
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Packet.buf)
}
inline ::std::string* Packet::mutable_buf() {
  
  // @@protoc_insertion_point(field_mutable:Packet.buf)
  return buf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Packet::release_buf() {
  // @@protoc_insertion_point(field_release:Packet.buf)
  
  return buf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Packet::set_allocated_buf(::std::string* buf) {
  if (buf != NULL) {
    
  } else {
    
  }
  buf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buf);
  // @@protoc_insertion_point(field_set_allocated:Packet.buf)
}

// repeated .Frag frags = 25;
inline int Packet::frags_size() const {
  return frags_.size();
}
inline void Packet::clear_frags() {
  frags_.Clear();
}
inline const ::Frag& Packet::frags(int index) const {
  // @@protoc_insertion_point(field_get:Packet.frags)
  return frags_.Get(index);
}
inline ::Frag* Packet::mutable_frags(int index) {
  // @@protoc_insertion_point(field_mutable:Packet.frags)
  return frags_.Mutable(index);
}
inline ::Frag* Packet::add_frags() {
  // @@protoc_insertion_point(field_add:Packet.frags)
  return frags_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Frag >*
Packet::mutable_frags() {
  // @@protoc_insertion_point(field_mutable_list:Packet.frags)
  return &frags_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Frag >&
Packet::frags() const {
  // @@protoc_insertion_point(field_list:Packet.frags)
  return frags_;
}

// int32 sampleRate = 26;
inline void Packet::clear_samplerate() {
  samplerate_ = 0;
}
inline ::google::protobuf::int32 Packet::samplerate() const {
  // @@protoc_insertion_point(field_get:Packet.sampleRate)
  return samplerate_;
}
inline void Packet::set_samplerate(::google::protobuf::int32 value) {
  
  samplerate_ = value;
  // @@protoc_insertion_point(field_set:Packet.sampleRate)
}

// int32 bitsPerSample = 27;
inline void Packet::clear_bitspersample() {
  bitspersample_ = 0;
}
inline ::google::protobuf::int32 Packet::bitspersample() const {
  // @@protoc_insertion_point(field_get:Packet.bitsPerSample)
  return bitspersample_;
}
inline void Packet::set_bitspersample(::google::protobuf::int32 value) {
  
  bitspersample_ = value;
  // @@protoc_insertion_point(field_set:Packet.bitsPerSample)
}

// int32 nChannels = 28;
inline void Packet::clear_nchannels() {
  nchannels_ = 0;
}
inline ::google::protobuf::int32 Packet::nchannels() const {
  // @@protoc_insertion_point(field_get:Packet.nChannels)
  return nchannels_;
}
inline void Packet::set_nchannels(::google::protobuf::int32 value) {
  
  nchannels_ = value;
  // @@protoc_insertion_point(field_set:Packet.nChannels)
}

// int32 nFrames = 29;
inline void Packet::clear_nframes() {
  nframes_ = 0;
}
inline ::google::protobuf::int32 Packet::nframes() const {
  // @@protoc_insertion_point(field_get:Packet.nFrames)
  return nframes_;
}
inline void Packet::set_nframes(::google::protobuf::int32 value) {
  
  nframes_ = value;
  // @@protoc_insertion_point(field_set:Packet.nFrames)
}

// -------------------------------------------------------------------

// OnTrackPacketMsg

// uint64 pcid = 30;
inline void OnTrackPacketMsg::clear_pcid() {
  pcid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OnTrackPacketMsg::pcid() const {
  // @@protoc_insertion_point(field_get:OnTrackPacketMsg.pcid)
  return pcid_;
}
inline void OnTrackPacketMsg::set_pcid(::google::protobuf::uint64 value) {
  
  pcid_ = value;
  // @@protoc_insertion_point(field_set:OnTrackPacketMsg.pcid)
}

// .Packet pkt = 31;
inline bool OnTrackPacketMsg::has_pkt() const {
  return this != internal_default_instance() && pkt_ != NULL;
}
inline void OnTrackPacketMsg::clear_pkt() {
  if (GetArenaNoVirtual() == NULL && pkt_ != NULL) delete pkt_;
  pkt_ = NULL;
}
inline const ::Packet& OnTrackPacketMsg::pkt() const {
  // @@protoc_insertion_point(field_get:OnTrackPacketMsg.pkt)
  return pkt_ != NULL ? *pkt_
                         : *::Packet::internal_default_instance();
}
inline ::Packet* OnTrackPacketMsg::mutable_pkt() {
  
  if (pkt_ == NULL) {
    pkt_ = new ::Packet;
  }
  // @@protoc_insertion_point(field_mutable:OnTrackPacketMsg.pkt)
  return pkt_;
}
inline ::Packet* OnTrackPacketMsg::release_pkt() {
  // @@protoc_insertion_point(field_release:OnTrackPacketMsg.pkt)
  
  ::Packet* temp = pkt_;
  pkt_ = NULL;
  return temp;
}
inline void OnTrackPacketMsg::set_allocated_pkt(::Packet* pkt) {
  delete pkt_;
  pkt_ = pkt;
  if (pkt) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OnTrackPacketMsg.pkt)
}

// -------------------------------------------------------------------

// AddTracksReq

// uint64 pcid = 32;
inline void AddTracksReq::clear_pcid() {
  pcid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddTracksReq::pcid() const {
  // @@protoc_insertion_point(field_get:AddTracksReq.pcid)
  return pcid_;
}
inline void AddTracksReq::set_pcid(::google::protobuf::uint64 value) {
  
  pcid_ = value;
  // @@protoc_insertion_point(field_set:AddTracksReq.pcid)
}

// repeated .TrackSrc trackSrcs = 33;
inline int AddTracksReq::tracksrcs_size() const {
  return tracksrcs_.size();
}
inline void AddTracksReq::clear_tracksrcs() {
  tracksrcs_.Clear();
}
inline const ::TrackSrc& AddTracksReq::tracksrcs(int index) const {
  // @@protoc_insertion_point(field_get:AddTracksReq.trackSrcs)
  return tracksrcs_.Get(index);
}
inline ::TrackSrc* AddTracksReq::mutable_tracksrcs(int index) {
  // @@protoc_insertion_point(field_mutable:AddTracksReq.trackSrcs)
  return tracksrcs_.Mutable(index);
}
inline ::TrackSrc* AddTracksReq::add_tracksrcs() {
  // @@protoc_insertion_point(field_add:AddTracksReq.trackSrcs)
  return tracksrcs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::TrackSrc >*
AddTracksReq::mutable_tracksrcs() {
  // @@protoc_insertion_point(field_mutable_list:AddTracksReq.trackSrcs)
  return &tracksrcs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::TrackSrc >&
AddTracksReq::tracksrcs() const {
  // @@protoc_insertion_point(field_list:AddTracksReq.trackSrcs)
  return tracksrcs_;
}

// -------------------------------------------------------------------

// Empty

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::TrackType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TrackType>() {
  return ::TrackType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rpc_2eproto__INCLUDED
